CREATE TABLE USUARIO(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 	LOGIN_USER VARCHAR(64) NOT NULL,
	SENHA_USER VARCHAR(80)
);


CREATE TABLE PARAFUSO( 
	ID_PARAFUSO INT(40) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	TIPO VARCHAR(255),
	QUANTIDADE int,
	LARGURA int,
	COMPRIMENTO int,
	USUARIO_ID int,
	CONSTRAINT USR_TCL_FK FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID) 

);
